/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/BjHkzKdhoAA
 */
import { CardContent, Card } from "@/components/ui/card"
import Image from 'next/image'
import Link from "next/link"


export function projectCard({title, link, img}: CardInfo) {
  return (
    <section className="w-full" key={title}>
      <div className="relative hover:cursor-pointer">
        <Link href={link}>
        <Image
          alt="Project 1"
          className="w-full h-full object-cover transform hover:scale-105 transition-transform duration-200"
          height="1000"
          src={img}
          style={{
            aspectRatio: "200/200",
            objectFit: "cover",
          }}
          width="1000"
        />
        <div className="absolute inset-0 bg-black bg-opacity-40 hover:bg-opacity-25 transition-opacity duration-200 flex items-center justify-center">
          <CardContent className="p-4 text-center">
            <h2 className="text-lg font-bold text-white">{title}</h2>
          </CardContent>
        </div>
        </Link>
      </div>
    </section>
  )
}

